version: '3'
services:
  web:
    build:
      context: ./flask_app
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes: ['./flask_app:/app']
    environment:
      FLASK_ENV: development
      FLASK_DEBUG: 1
    command: flask run --host=0.0.0.0 
    depends_on:
      - redis
  worker:
    build:
      context: ./celery_app
      dockerfile: Dockerfile
    volumes: ['./celery_app:/celery_app']
    depends_on:
      - redis
  monitor:
    build:
      context: ./celery_app
      dockerfile: Dockerfile
    ports:
     - "5555:5555"
    entrypoint: flower
    command:  -A tasks --port=5555 --broker=redis://redis:6379/0
    depends_on:
      - redis
  redis:
    image: redis